export const SET_CHECK_ITEM_DEL = 'SET_CHECK_ITEM_DEL'
export const SET_CHECK_ITEM_DELDEL = 'SET_CHECK_ITEM_DELDDEL'
export const SET_CHECK_ITEM_DEL_ALL = 'SET_CHECK_ITEM_DEL_ALL'
export const SET_CHECK_ITEM_DELDEL_ALL = 'SET_CHECK_ITEM_DELDEL_ALL'